version: "3.8"

services:
  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    restart: always
    ports:
      - "8080:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - SQLITE_DATABASE=nextcloud
    volumes:
      - nextcloud_data:/var/www/html

  locust:
    image: locustio/locust
    container_name: locust
    command: -f /locust-tasks/tasks.py --host=http://nextcloud
    ports:
      - "8089:8089"
    volumes:
      - ./locust-tasks:/locust-tasks
      - ./test-data:/test-data

  prometheus:
    image: prom/prometheus@sha256:bc1794e85c9e00293351b967efa267ce6af1c824ac875a9d0c7ac84700a8b53e
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"

  nextcloud-exporter:
    image: ghcr.io/xperimental/nextcloud-exporter@sha256:355c8d0d370d8b45551146764613ae078ca99f64d11453339f3d57c295b4b9a4
    container_name: nextcloud-exporter
    restart: always
    environment:
      - NEXTCLOUD_SERVER=http://nextcloud
      - NEXTCLOUD_USERNAME=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_LISTEN_ADDRESS=:9205
    ports:
      - "9205:9205"

  grafana:
    image: 
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

volumes:
  nextcloud_data:
  grafana_data:
  prometheus_data:
